# Generated by Django 5.1 on 2024-09-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название объекта')),
                ('number_of_room', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('square', models.PositiveSmallIntegerField(verbose_name='Площадь')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Площадь')),
                ('adult', models.PositiveSmallIntegerField(verbose_name='Количество взрослых')),
                ('kid', models.PositiveSmallIntegerField(verbose_name='Количество детей')),
                ('average_rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг объекта')),
                ('sea_distance', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('view', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_by_address', to='booking.address', verbose_name='Адрес')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_objects', to=settings.AUTH_USER_MODEL, verbose_name='Собственник')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
