# Generated by Django 5.1 on 2024-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_object_floor_alter_object_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг объекта'),
        ),
    ]
