# Generated by Django 5.1 on 2024-09-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_object_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='address',
            name='entrance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AddField(
            model_name='address',
            name='house',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=1, max_length=255, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
