# Generated by Django 5.1 on 2024-09-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_address_latitude_alter_address_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object_by_address', to='booking.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_objects', to=settings.AUTH_USER_MODEL, verbose_name='Собственник'),
        ),
    ]
