# Generated by Django 5.1 on 2024-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_object_address_alter_object_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='number_of_floors',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество этажей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Объявление активно'),
        ),
        migrations.AlterField(
            model_name='object',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
