# Generated by Django 5.1 on 2024-10-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_object_number_of_floors_alter_object_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='objects/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок картинки')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.object', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок видео')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='booking.object', verbose_name='Объект')),
            ],
        ),
    ]
