# Generated by Django 5.1 on 2024-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(related_name='tag_objects', to='booking.tag', verbose_name='Теги'),
        ),
    ]
