# Generated by Django 5.1 on 2024-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_tag_options_object_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='tags',
        ),
        migrations.AddField(
            model_name='independentobject',
            name='tags',
            field=models.ManyToManyField(related_name='independent_objects', to='booking.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(related_name='rooms', to='booking.tag', verbose_name='Теги'),
        ),
    ]
