# Generated by Django 5.1 on 2024-10-17 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_object_tags_independentobject_tags_room_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='user_favorites',
            field=models.ManyToManyField(related_name='favorites_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
