# Generated by Django 5.1 on 2024-11-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_object_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default=1, upload_to='cites/', verbose_name='Изображение города'),
            preserve_default=False,
        ),
    ]
