# Generated by Django 5.1 on 2024-11-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_tagtype_tag_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagtype',
            options={'verbose_name': 'Тип тега', 'verbose_name_plural': 'Тиы тегов'},
        ),
    ]
