# Generated by Django 5.1 on 2024-11-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_data_of_birth_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Страна')),
            ],
        ),
        migrations.AddField(
            model_name='fellowtraveler',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travelers', to='users.citizenship', verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.citizenship', verbose_name='Гражданство'),
        ),
    ]
