# Generated by Django 5.1 on 2024-11-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_citizenship_fellowtraveler_citizenship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellowtraveler',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fellowtraveler',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='fellowtraveler',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='fellowtraveler',
            name='data_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='fellowtraveler',
            name='sex',
            field=models.CharField(blank=True, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='fellowtraveler',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to='users.citizenship', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to='users.citizenship', verbose_name='Гражданство'),
        ),
    ]
