# Generated by Django 5.1 on 2024-11-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_first_name_fellowtraveler_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellowtraveler',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
