# Generated by Django 5.1 on 2024-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_data_of_birth_fellowtraveler_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowtraveler',
            name='sex',
            field=models.CharField(blank=True, choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], null=True, verbose_name='Пол'),
        ),
    ]
